[package]
name = "occlum-ra"
version = "0.1.0"
edition = "2021"

[dependencies]
webpki-roots = { version = "0.21", optional = true }
pem = { version = "0.8", optional = true }
yasna   = { git = "https://github.com/sgx-test/yasna.rs", features = ["bit-vec", "num-bigint", "chrono"], optional = true }
rand_core = { version = "0.5.1", features = ["getrandom"], optional = true }
num-bigint = { version = "0.4.2", optional = true }
chrono  = { version = "0.4.19", default-features = false }
sha2 = { version = "^0.8", default-features = false }
webpki = { version = "0.21.4", default-features = false }
base64 = { version = "0.9.2", default-features = false }
log = { version = "0.4.14", default-features = false }
ring = { version = "*", default-features = false, features = ["alloc"] }
hex = { version = "0.4", default-features = false }
sgx_types = { git = "https://github.com/occlum/incubator-teaclave-sgx-sdk" }
serde = { version = "1.0", default-features = false, features = ["derive", "alloc"] }
serde_json = { version = "1.0", default-features = false, features = ["alloc"] }
itertools = { version = "0.8", default-features = false }
bit-vec = "*"
httparse = { version = "1.3.2", default-features = false }
http_req = { version = "0.9.0", default-features = false, features = ["rust-tls"] }
rustls = { version = "0.19", default-features = false, features = ["dangerous_configuration"] }
rand =  { version = "0.8.5"}
occlum_dcap = { git = "https://github.com/ABMatrix/occlum", optional = true }

[patch.crates-io]
ring = { git = "https://github.com/sgx-test/ring" ,default-features = false, features = ["alloc"] }

[features]
default = ["std"]
no_std = []
std = [
    "webpki-roots",
    "pem",
    "yasna",
    "rand_core",
    "num-bigint",
    "occlum_dcap"
]